sim-setup:
  nstep: 17000
  dt: 1.25e-4
  display-types:
    - rotation
    - displacement
  display-time-interval: 1000
  wavefield-time-interval: 170
  nspecx: 400
  nspecz: 400
  Lx: 10000
  Lz: 10000

boundary-conditions:
  use-stacey: false
  absorb-bottom: false
  absorb-right: false
  absorb-top: false
  absorb-left: false

materials:
# for now we just assume one material
  - type: cosserat
    properties:
      rho: "2.70d+03"
      kappa: "3.96d+10"
      mu: "1.06d+10"
      nu: "3.49d+05"
      j: "4.02d+02"
      lambda-c: "3.16d+06"
      mu-c: "5.61d+08"
      nu-c: "4.39d+02"

station-sets:
  - nrec: 4
    xdeb: 6000
    zdeb: 6000
    xfin: 7000
    zfin: 7000
    record_at_surface_same_vertical: false

cosserat-sources:
  - type: Ricker
    x: 5000.0
    z: 5000.0
    source_surf: false
    angle: 0.0
    f: 1.0
    fc: 1.0
    Ricker:
      factor: 1e10
      tshift: 0.0
      f0: 11.674557134373474
